repos:
    # hooks for checking files
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.6.0
        hooks:
            -   id: trailing-whitespace
            -   id: end-of-file-fixer
            -   id: check-yaml

    # hooks for linting code
    -   repo: local
        hooks:
            -   id: ruff
                name: ruff
                entry: ruff check --config pyproject.toml --force-exclude
                language: unsupported
                types_or: [python, pyi]
