name: "🐞 Bug Report"
description: Submit a bug report to help us improve PyPOTS.
labels: ["bug"]

body:
  - type: textarea
    id: system-info
    attributes:
      label: 1. System Info
      description: Please share information about your operating environment with us.
      placeholder: PyPOTS version, Python version, platform and your OS version, and versions of other libraries existing in the error message...
    validations:
      required: true

  - type: checkboxes
    id: information-scripts-examples
    attributes:
      label: 2. Information
      description: 'The problem happens when running:'
      options:
        - label: "The official example scripts"
        - label: "My own created scripts"

  - type: textarea
    id: reproduction
    validations:
      required: true
    attributes:
      label: 3. Reproduction
      description: |
        Please provide a code sample that reproduces the problem you ran into. It can be a Colab link or just a code snippet.
        If you have code snippets, error messages, stack traces please provide them here as well.
        Important! Use code tags to correctly format your code. See https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks#syntax-highlighting
        Do not use screenshots, as they are hard to read and (more importantly) don't allow others to copy-and-paste your code.

      placeholder: |
        Steps to reproduce the behavior:

          1.
          2.
          3.

          ……


  - type: textarea
    id: expected-behavior
    validations:
      required: true
    attributes:
      label: 4. Expected behavior
      description: | 
        A clear and concise description of what error you would expect to happen.
        Please provide the whole "Traceback" of the error message printed in the console.
