import os
import glob
import ast
import re

TASKS = ["imputation", "classification", "clustering", "forecasting", "anomaly_detection"]
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEST_DIR = os.path.join(PROJECT_ROOT, "tests")
EXAMPLES_DIR = os.path.join(PROJECT_ROOT, "examples")

TEMPLATES = {
    "imputation": """\
\"\"\"
A minimalist, standalone example of the PyPOTS {model_name} model for time-series imputation.
This script is auto-generated by extracting hyperparameters from the test code.
\"\"\"

import numpy as np
from pypots.imputation import {model_name}
from pypots.utils.metrics import calc_mse
from pygrinder import mcar

def main():
    n_samples = 200
    n_steps = 48
    n_features = 35

    # 1. Generate a complete random time-series as the ground truth
    X_intact = np.random.randn(n_samples, n_steps, n_features)

    # 2. Introduce random missing values (10% missing rate)
    X_missing = mcar(X_intact, p=0.1)

    # 3. Split into training and test sets
    train_set = {{"X": X_missing[:150], "X_ori": X_intact[:150]}}
    test_set = {{"X": X_missing[150:], "X_ori": X_intact[150:]}}
    test_X_intact = X_intact[150:]

    # 4. Initialize the model
    model = {init_code}

    # 5. Train the model
    print("🚀 Training the {model_name} model...")
    model.fit(train_set)

    # 6. Impute missing values
    print("🔮 Imputing missing values...")
    results = model.predict(test_set)
    imputed_X = results["imputation"]
    if len(imputed_X.shape) == 4:
        imputed_X = imputed_X.mean(axis=1)

    # 7. Evaluate
    indicating_mask = np.isnan(test_set["X"])
    mse = calc_mse(imputed_X, test_X_intact, indicating_mask)
    print(f"✅ The MSE of {model_name} imputation is: {{mse:.4f}}")

if __name__ == "__main__":
    main()
""",
    "classification": """\
\"\"\"
A minimalist, standalone example of the PyPOTS {model_name} model for time-series classification.
This script is auto-generated by extracting hyperparameters from the test code.
\"\"\"

import numpy as np
from pypots.classification import {model_name}

def main():
    n_samples = 200
    n_steps = 48
    n_features = 35
    n_classes = 5

    # 1. Generate random time-series features and integer classification labels
    X = np.random.randn(n_samples, n_steps, n_features)
    y = np.random.randint(0, n_classes, n_samples)

    # 2. Split into training and test sets
    train_set = {{"X": X[:150], "y": y[:150]}}
    test_set = {{"X": X[150:]}}
    test_y_true = y[150:]

    # 3. Initialize the model
    model = {init_code}

    # 4. Train the model
    print("🚀 Training the {model_name} model...")
    model.fit(train_set)

    # 5. Predict classification labels
    print("🔮 Predicting classification labels...")
    results = model.predict(test_set)
    
    # 6. Evaluate accuracy
    predictions = results["classification"]
    acc = np.mean(predictions == test_y_true)
    print(f"✅ The Accuracy of {model_name} classification is: {{acc:.4f}}")

if __name__ == "__main__":
    main()
""",
    "clustering": """\
\"\"\"
A minimalist, standalone example of the PyPOTS {model_name} model for time-series clustering.
This script is auto-generated by extracting hyperparameters from the test code.
\"\"\"

import numpy as np
from pypots.clustering import {model_name}

def main():
    n_samples = 200
    n_steps = 48
    n_features = 35
    n_classes = 5
    n_clusters = 5

    # 1. Generate random time-series features (no labels required)
    X = np.random.randn(n_samples, n_steps, n_features)

    # 2. Split into training and test sets
    train_set = {{"X": X[:150]}}
    test_set = {{"X": X[150:]}}

    # 3. Initialize the model
    model = {init_code}

    # 4. Train the model
    print("🚀 Training the {model_name} clustering model...")
    model.fit(train_set)

    # 5. Predict clusters
    print("🔮 Predicting clusters for the test set...")
    results = model.predict(test_set)
    clusters = results["clustering"]
    
    print(f"✅ {model_name} successfully output cluster assignments.")

if __name__ == "__main__":
    main()
""",
    "forecasting": """\
\"\"\"
A minimalist, standalone example of the PyPOTS {model_name} model for time-series forecasting.
This script is auto-generated by extracting hyperparameters from the test code.
\"\"\"

import numpy as np
from pypots.forecasting import {model_name}

def main():
    n_samples = 200
    n_steps = 48
    n_features = 35
    n_pred_steps = 12

    # 1. Generate random time-series features
    X = np.random.randn(n_samples, n_steps, n_features)
    X_pred = np.random.randn(n_samples, n_pred_steps, n_features)

    # 2. Split into training and test sets
    train_set = {{"X": X[:150], "X_pred": X_pred[:150]}}
    test_set = {{"X": X[150:], "X_pred": X_pred[150:]}}

    # 3. Initialize the model
    model = {init_code}

    # 4. Train the model
    print("🚀 Training the {model_name} forecasting model...")
    model.fit(train_set)

    # 5. Forecast
    print("🔮 Forecasting future steps...")
    results = model.predict(test_set)
    forecasts = results["forecasting"]
    
    print(f"✅ {model_name} successfully forecasted future steps, output shape: {{forecasts.shape}}")

if __name__ == "__main__":
    main()
""",
    "anomaly_detection": """\
\"\"\"
A minimalist, standalone example of the PyPOTS {model_name} model for time-series anomaly detection.
This script is auto-generated by extracting hyperparameters from the test code.
\"\"\"

import numpy as np
from pypots.anomaly_detection import {model_name}

def main():
    n_samples = 200
    n_steps = 48
    n_features = 35

    # 1. Generate normal random time-series features
    X = np.random.randn(n_samples, n_steps, n_features)

    # 2. Split into training and test sets
    train_set = {{"X": X[:150]}}
    test_set = {{"X": X[150:]}}

    # 3. Initialize the model
    model = {init_code}

    # 4. Train the model
    print("🚀 Training the {model_name} anomaly detection model...")
    model.fit(train_set)

    # 5. Calculate anomaly scores
    print("🔮 Calculating anomaly scores for the test set...")
    results = model.predict(test_set)
    scores = results["anomaly_detection"]
    
    print(f"✅ {model_name} successfully calculated anomaly scores, score shape: {{scores.shape}}")

if __name__ == "__main__":
    main()
"""
}

def extract_clean_init_code(source_code, node):
    init_code = ast.get_source_segment(source_code, node)
    if not init_code:
        return ""

    init_code = init_code.replace('DATA["n_steps"]', 'n_steps')
    init_code = init_code.replace('DATA["n_features"]', 'n_features')
    init_code = init_code.replace('DATA["n_classes"]', 'n_classes')
    init_code = init_code.replace('DATA["n_clusters"]', 'n_clusters')
    init_code = init_code.replace('DATA["n_pred_steps"]', 'n_pred_steps')
    init_code = init_code.replace('N_PRED_STEPS', 'n_pred_steps')
    init_code = init_code.replace('n_steps - n_pred_steps', 'n_steps')
    init_code = init_code.replace('DATA["anomaly_rate"]', '0.05')
    init_code = init_code.replace('EPOCHS', '2')
    init_code = init_code.replace('DEVICE', '"cpu"')

    # Fix HELIX lr issue by injecting lr parameter when optimizing isn't explicitly passed
    if "HELIX" in init_code and "lr=" not in init_code:
        init_code = init_code.replace("device=", "lr=1e-3, device=")

    init_code = re.sub(r'\n\s*saving_path=[^,)]+,?', '', init_code)
    init_code = re.sub(r'\n\s*optimizer=[^,)]+,?', '', init_code)
    init_code = re.sub(r'\n\s*G_optimizer=[^,)]+,?', '', init_code)
    init_code = re.sub(r'\n\s*D_optimizer=[^,)]+,?', '', init_code)

    return init_code

def main():
    print("🔍 Scanning tests directory and generating examples...")
    for task in TASKS:
        task_dir = os.path.join(TEST_DIR, task)
        output_dir = os.path.join(EXAMPLES_DIR, task)
        os.makedirs(output_dir, exist_ok=True)

        test_files = glob.glob(os.path.join(task_dir, "*.py"))

        for file in test_files:
            basename = os.path.basename(file)
            if basename.startswith("__"):
                continue

            with open(file, "r", encoding="utf-8") as f:
                source = f.read()

            try:
                tree = ast.parse(source)
            except SyntaxError:
                continue

            model_name = None
            init_code = None

            for node in tree.body:
                if isinstance(node, ast.ClassDef) and node.name.startswith("Test"):
                    for item in node.body:
                        if isinstance(item, ast.Assign) and isinstance(item.value, ast.Call):
                            func = item.value.func
                            if isinstance(func, ast.Name):
                                temp_name = func.id
                                if temp_name.isupper() or temp_name.istitle():
                                    if temp_name not in ["Adam", "SGD", "SummaryWriter"]:
                                        model_name = temp_name
                                        init_code = extract_clean_init_code(source, item.value)
                                        break

            if model_name == "TRMF": continue
            if model_name == "HELIX": continue
            if model_name == "Raindrop": continue
            if model_name == "FITS" and task == "imputation": continue

            if model_name and init_code:
                example_code = TEMPLATES[task].format(
                    model_name=model_name,
                    init_code=init_code
                )

                task_str = task.replace("_", "")
                example_filename = basename.replace(".py", f"_{task_str}_example.py")
                output_path = os.path.join(output_dir, example_filename)

                with open(output_path, "w", encoding="utf-8") as f:
                    f.write(example_code)
                print(f"✅ Generated {task}/{example_filename} (extracted model: {model_name})")

if __name__ == "__main__":
    main()
