import ast
import glob
import os
import re

TASKS = ["imputation", "classification", "clustering", "forecasting", "anomaly_detection"]
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEST_DIR = os.path.join(PROJECT_ROOT, "tests")
EXAMPLES_DIR = os.path.join(PROJECT_ROOT, "examples")

TEMPLATES = {
    "imputation": """\
\"\"\"
A minimalist, standalone example of the PyPOTS {model_name} model for time-series imputation.
This script is auto-generated by extracting hyperparameters from the test code.
\"\"\"

import numpy as np
from benchpots.datasets import preprocess_random_walk
from pypots.imputation import {model_name}
from pypots.utils.metrics import calc_mse

def main():
    n_steps = 48
    n_features = 35

    # 1. Generate a random walk time-series dataset
    dataset = preprocess_random_walk(n_steps=n_steps, n_features=n_features, n_classes=5, n_samples_each_class=40, missing_rate=0.1)

    # 2. Extract training and test sets
    train_set = {{"X": dataset["train_X"], "X_ori": dataset["train_X_ori"]}}
    val_set = {{"X": dataset["val_X"], "X_ori": dataset["val_X_ori"]}}
    test_set = {{"X": dataset["test_X"], "X_ori": dataset["test_X_ori"]}}
    test_X_intact = dataset["test_X_ori"]

    # 3. Initialize the model
    model = {init_code}

    # 4. Train the model
    print("🚀 Training the {model_name} model...")
    model.fit(train_set, val_set)

    # 5. Impute missing values
    print("🔮 Imputing missing values...")
    results = model.predict(test_set)
    imputed_X = results["imputation"]

    # 6. Evaluate
    indicating_mask = np.isnan(test_set["X"])
    mse = calc_mse(imputed_X, test_X_intact, indicating_mask)
    print(f"✅ The MSE of {model_name} imputation is: {{mse:.4f}}")

if __name__ == "__main__":
    main()
""",
    "classification": """\
\"\"\"
A minimalist, standalone example of the PyPOTS {model_name} model for time-series classification.
This script is auto-generated by extracting hyperparameters from the test code.
\"\"\"

import numpy as np
from benchpots.datasets import preprocess_random_walk
from pypots.classification import {model_name}
from pypots.nn.functional import calc_binary_classification_metrics

def main():
    n_steps = 48
    n_features = 35
    n_classes = 2

    # 1. Generate a random walk time-series dataset
    dataset = preprocess_random_walk(n_steps=n_steps, n_features=n_features, n_classes=n_classes, n_samples_each_class=100, missing_rate=0.1)

    # 2. Extract training and test sets
    train_set = {{"X": dataset["train_X"], "y": dataset["train_y"]}}
    val_set = {{"X": dataset["val_X"], "y": dataset["val_y"]}}
    test_set = {{"X": dataset["test_X"]}}
    test_y_true = dataset["test_y"]

    # 3. Initialize the model
    model = {init_code}

    # 4. Train the model
    print("🚀 Training the {model_name} model...")
    model.fit(train_set, val_set)

    # 5. Predict classification labels
    print("🔮 Predicting classification labels...")
    results = model.predict(test_set)
    
    # 6. Evaluate accuracy
    proba_predictions = results["classification_proba"]
    metrics = calc_binary_classification_metrics(proba_predictions, test_y_true)
    print(f'✅ {model_name} classification ROC_AUC: {{metrics["roc_auc"]:.4f}}, '
          f'PR_AUC: {{metrics["pr_auc"]:.4f}}, '
          f'F1: {{metrics["f1"]:.4f}}, '
          f'Precision: {{metrics["precision"]:.4f}}, '
          f'Recall: {{metrics["recall"]:.4f}}')

if __name__ == "__main__":
    main()
""",
    "clustering": """\
\"\"\"
A minimalist, standalone example of the PyPOTS {model_name} model for time-series clustering.
This script is auto-generated by extracting hyperparameters from the test code.
\"\"\"

import numpy as np
from benchpots.datasets import preprocess_random_walk
from pypots.clustering import {model_name}
from pypots.nn.functional import calc_external_cluster_validation_metrics

def main():
    n_steps = 48
    n_features = 35
    n_classes = 5
    n_clusters = 5

    # 1. Generate a random walk time-series dataset
    dataset = preprocess_random_walk(n_steps=n_steps, n_features=n_features, n_classes=n_classes, n_samples_each_class=40, missing_rate=0.1)

    # 2. Extract training and test sets
    train_set = {{"X": dataset["train_X"]}}
    val_set = {{"X": dataset["val_X"]}}
    test_set = {{"X": dataset["test_X"]}}
    test_y_true = dataset["test_y"]

    # 3. Initialize the model
    model = {init_code}

    # 4. Train the model
    print("🚀 Training the {model_name} clustering model...")
    model.fit(train_set)

    # 5. Predict clusters
    print("🔮 Predicting clusters for the test set...")
    results = model.predict(test_set)
    clusters = results["clustering"]
    
    # 6. Evaluate
    metrics = calc_external_cluster_validation_metrics(clusters, test_y_true)
    print(f"✅ {model_name} clustering external metrics: \\n"
          f"CR: {{metrics['rand_index']:.4f}}, Purity: {{metrics['cluster_purity']:.4f}}, NMI: {{metrics['nmi']:.4f}}")

if __name__ == "__main__":
    main()
""",
    "forecasting": """\
\"\"\"
A minimalist, standalone example of the PyPOTS {model_name} model for time-series forecasting.
This script is auto-generated by extracting hyperparameters from the test code.
\"\"\"

import numpy as np
from benchpots.datasets import preprocess_random_walk
from pypots.nn.functional import calc_mse
from pypots.forecasting import {model_name}

def main():
    n_steps = 48
    n_pred_steps = 12
    n_features = 35

    # 1. Generate a random walk time-series dataset
    dataset = preprocess_random_walk(n_steps=n_steps + n_pred_steps, n_features=n_features, n_classes=5, n_samples_each_class=40, missing_rate=0.1)

    # 2. Extract training and test sets
    train_X = dataset["train_X"]
    val_X = dataset["val_X"]
    test_X = dataset["test_X"]
    train_set = {{"X": train_X[:, :n_steps], "X_pred": train_X[:, n_steps:]}}
    val_set = {{"X": val_X[:, :n_steps], "X_pred": val_X[:, n_steps:]}}
    test_set = {{"X": test_X[:, :n_steps], "X_pred": test_X[:, n_steps:]}}

    # 3. Initialize the model
    model = {init_code}

    # 4. Train the model
    print("🚀 Training the {model_name} forecasting model...")
    model.fit(train_set, val_set)

    # 5. Forecast
    print("🔮 Forecasting future steps...")
    results = model.predict(test_set)
    forecasts = results["forecasting"]
    
    test_MSE = calc_mse(forecasts, np.nan_to_num(test_set["X_pred"]), ~np.isnan(test_set["X_pred"]))    
    print(f"✅ {model_name} forecasting MSE: {{test_MSE:.4f}}")

if __name__ == "__main__":
    main()
""",
    "anomaly_detection": """\
\"\"\"
A minimalist, standalone example of the PyPOTS {model_name} model for time-series anomaly detection.
This script is auto-generated by extracting hyperparameters from the test code.
\"\"\"

from benchpots.datasets import preprocess_random_walk
from pypots.anomaly_detection import {model_name}
from pypots.nn.functional import calc_acc, calc_precision_recall_f1

def main():
    n_steps = 48
    n_features = 35

    # 1. Generate a random walk time-series dataset
    dataset = preprocess_random_walk(n_steps=n_steps, n_features=n_features, n_classes=5, n_samples_each_class=40, missing_rate=0.1, anomaly_rate=0.05)

    # 2. Extract training and test sets
    train_set = {{"X": dataset["train_X"], "anomaly_y": dataset["train_anomaly_y"]}}
    val_set = {{"X": dataset["val_X"], "X_ori": dataset["val_X_ori"], "anomaly_y": dataset["val_anomaly_y"]}}
    test_set = {{"X": dataset["test_X"]}}
    test_anomaly_y = dataset["test_anomaly_y"].flatten()

    # 3. Initialize the model
    model = {init_code}

    # 4. Train the model
    print("🚀 Training the {model_name} anomaly detection model...")
    model.fit(train_set, val_set)

    # 5. Calculate anomaly scores
    print("🔮 Calculating anomaly scores for the test set...")
    results = model.predict(test_set)
    scores = results["anomaly_detection"]
    
    # 6. Evaluate
    accuracy = calc_acc(scores, test_anomaly_y)
    precision, recall, f1 = calc_precision_recall_f1(scores, test_anomaly_y)
    print(f"✅ {model_name} anomaly detection - Accuracy: {{accuracy:.4f}}, F1: {{f1:.4f}}, Precision: {{precision:.4f}}, Recall: {{recall:.4f}}")

if __name__ == "__main__":
    main()
""",
}


def extract_clean_init_code(source_code, node):
    init_code = ast.get_source_segment(source_code, node)
    if not init_code:
        return ""

    init_code = init_code.replace('DATA["n_steps"]', "n_steps")
    init_code = init_code.replace('DATA["n_features"]', "n_features")
    init_code = init_code.replace('DATA["n_classes"]', "n_classes")
    init_code = init_code.replace('DATA["n_clusters"]', "n_clusters")
    init_code = init_code.replace('DATA["n_pred_steps"]', "n_pred_steps")
    init_code = init_code.replace("N_PRED_STEPS", "n_pred_steps")
    init_code = init_code.replace("n_steps - n_pred_steps", "n_steps")
    init_code = init_code.replace('DATA["anomaly_rate"]', "0.05")
    init_code = init_code.replace("EPOCHS", "2")
    init_code = init_code.replace("DEVICE", '"cpu"')

    init_code = re.sub(r"\n\s*saving_path=[^,)]+,?", "", init_code)
    init_code = re.sub(r"\n\s*optimizer=[^,)]+,?", "", init_code)
    init_code = re.sub(r"\n\s*G_optimizer=[^,)]+,?", "", init_code)
    init_code = re.sub(r"\n\s*D_optimizer=[^,)]+,?", "", init_code)

    return init_code


def main():
    print("🔍 Scanning tests directory and generating examples...")
    for task in TASKS:
        task_dir = os.path.join(TEST_DIR, task)
        output_dir = os.path.join(EXAMPLES_DIR, task)
        os.makedirs(output_dir, exist_ok=True)

        test_files = glob.glob(os.path.join(task_dir, "*.py"))
        test_files.extend(glob.glob(os.path.join(task_dir, "llms/*.py")))

        for file in test_files:
            if os.path.isdir(file):
                continue

            basename = os.path.basename(file)
            if basename.startswith("__"):  # skip __init__.py and similar files
                continue

            print(file)
            with open(file, "r", encoding="utf-8") as f:
                source = f.read()

            try:
                tree = ast.parse(source)
            except SyntaxError:
                continue

            model_name = None
            init_code = None

            for node in tree.body:
                if isinstance(node, ast.ClassDef) and node.name.startswith("Test"):
                    for item in node.body:
                        if isinstance(item, ast.Assign) and isinstance(item.value, ast.Call):
                            func = item.value.func
                            if isinstance(func, ast.Name):
                                temp_name = func.id
                                if temp_name[0].isupper() or temp_name == "iTransformer":
                                    if temp_name not in ["Adam", "SGD", "SummaryWriter"]:
                                        model_name = temp_name
                                        init_code = extract_clean_init_code(source, item.value)
                                        break

            if model_name and init_code:
                example_code = TEMPLATES[task].format(model_name=model_name, init_code=init_code)

                task_str = task.replace("_", "")
                example_filename = basename.replace(".py", f"_{task_str}_example.py")
                output_path = os.path.join(output_dir, example_filename)

                with open(output_path, "w", encoding="utf-8") as f:
                    f.write(example_code)
                print(f"✅ Generated {task}/{example_filename} (extracted model: {model_name})")


if __name__ == "__main__":
    main()
