name: pypots

channels:
    - conda-forge
    - pytorch
    - nodefaults

dependencies:
    # basic
    - conda-forge::python >=3.8
    - conda-forge::pip
    - conda-forge::h5py
    - conda-forge::numpy <2.0
    - conda-forge::scipy
    - conda-forge::sympy
    - conda-forge::einops
    - conda-forge::pandas
    - conda-forge::seaborn
    - conda-forge::matplotlib
    - conda-forge::tensorboard
    - conda-forge::scikit-learn
    - conda-forge::transformers
    - conda-forge::pygrinder >=0.7
    - conda-forge::tsdb >=0.6.1
    - conda-forge::benchpots >=0.3.2
    - conda-forge::ai4ts
    - pytorch::pytorch >=1.10.0
