"""
A minimalist, standalone example of the PyPOTS TEFN model for time-series anomaly detection.
This script is auto-generated by extracting hyperparameters from the test code.
"""

from benchpots.datasets import preprocess_random_walk
from pypots.anomaly_detection import TEFN
from pypots.nn.functional import calc_acc, calc_precision_recall_f1


def main():
    n_steps = 48
    n_features = 35

    # 1. Generate a random walk time-series dataset
    dataset = preprocess_random_walk(
        n_steps=n_steps,
        n_features=n_features,
        n_classes=5,
        n_samples_each_class=40,
        missing_rate=0.1,
        anomaly_rate=0.05,
    )

    # 2. Extract training and test sets
    train_set = {"X": dataset["train_X"], "anomaly_y": dataset["train_anomaly_y"]}
    val_set = {"X": dataset["val_X"], "X_ori": dataset["val_X_ori"], "anomaly_y": dataset["val_anomaly_y"]}
    test_set = {"X": dataset["test_X"]}
    test_anomaly_y = dataset["test_anomaly_y"].flatten()

    # 3. Initialize the model
    model = TEFN(
        n_steps,
        n_features,
        anomaly_rate=0.05,
        n_fod=8,
        epochs=2,
        device="cpu",
    )

    # 4. Train the model
    print("🚀 Training the TEFN anomaly detection model...")
    model.fit(train_set, val_set)

    # 5. Calculate anomaly scores
    print("🔮 Calculating anomaly scores for the test set...")
    results = model.predict(test_set)
    scores = results["anomaly_detection"]

    # 6. Evaluate
    accuracy = calc_acc(scores, test_anomaly_y)
    precision, recall, f1 = calc_precision_recall_f1(scores, test_anomaly_y)
    print(
        f"✅ TEFN anomaly detection - Accuracy: {accuracy:.4f}, F1: {f1:.4f}, Precision: {precision:.4f}, Recall: {recall:.4f}"
    )


if __name__ == "__main__":
    main()
