name: Linting

on:
    push:
        branches:
            - main
            - dev
    pull_request:
        branches:
            - main
            - dev

jobs:
    ruff-linting:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v6

            - name: Set up Python
              uses: actions/setup-python@v6
              with:
                  python-version: "3.13"

            - name: Install Ruff
              run: |
                pip install ruff

            - name: Run linting
              run: |
                ruff check .
