"""
A minimalist, standalone example of the PyPOTS TOTEM model for time-series imputation.
This script is auto-generated by extracting hyperparameters from the test code.
"""

import numpy as np
from benchpots.datasets import preprocess_random_walk
from pypots.imputation import TOTEM
from pypots.utils.metrics import calc_mse


def main():
    n_steps = 48
    n_features = 35

    # 1. Generate a random walk time-series dataset
    dataset = preprocess_random_walk(
        n_steps=n_steps, n_features=n_features, n_classes=5, n_samples_each_class=40, missing_rate=0.1
    )

    # 2. Extract training and test sets
    train_set = {"X": dataset["train_X"], "X_ori": dataset["train_X_ori"]}
    val_set = {"X": dataset["val_X"], "X_ori": dataset["val_X_ori"]}
    test_set = {"X": dataset["test_X"], "X_ori": dataset["test_X_ori"]}
    test_X_intact = dataset["test_X_ori"]

    # 3. Initialize the model
    model = TOTEM(
        n_steps,
        n_features,
        d_block_hidden=64,
        n_residual_layers=2,
        d_residual_hidden=32,
        d_embedding=32,
        n_embeddings=128,
        commitment_cost=0.25,
        compression_factor=4,
        epochs=2,
        device="cpu",
    )

    # 4. Train the model
    print("🚀 Training the TOTEM model...")
    model.fit(train_set, val_set)

    # 5. Impute missing values
    print("🔮 Imputing missing values...")
    results = model.predict(test_set)
    imputed_X = results["imputation"]

    # 6. Evaluate
    indicating_mask = np.isnan(test_set["X"])
    mse = calc_mse(imputed_X, test_X_intact, indicating_mask)
    print(f"✅ The MSE of TOTEM imputation is: {mse:.4f}")


if __name__ == "__main__":
    main()
