"""
A minimalist, standalone example of the PyPOTS TRMF model for time-series imputation.
This script is auto-generated by extracting hyperparameters from the test code.
"""

import numpy as np
from benchpots.datasets import preprocess_random_walk
from pypots.imputation import TRMF
from pypots.utils.metrics import calc_mse


def main():
    n_steps = 48
    n_features = 35

    # 1. Generate a random walk time-series dataset
    dataset = preprocess_random_walk(
        n_steps=n_steps, n_features=n_features, n_classes=5, n_samples_each_class=40, missing_rate=0.1
    )

    # 2. Extract training and test sets
    train_set = {"X": dataset["train_X"]}
    val_set = {"X": dataset["val_X"], "X_ori": dataset["val_X_ori"]}
    train_X_intact = dataset["train_X_ori"]

    # 3. Initialize the model
    model = TRMF(
        (1, 5),
        K=8,
        lambda_f=1,
        lambda_x=1,
        lambda_w=1,
        alpha=1,
        eta=1000,
        max_iter=1000,
    )

    # 4. Train the model
    print("🚀 Training the TRMF model...")
    model.fit(train_set, val_set)

    # 5. Impute missing values
    print("🔮 Imputing missing values...")
    results = model.predict(train_set)
    imputed_X = results["imputation"]

    # 6. Evaluate
    indicating_mask = np.isnan(train_set["X"])
    mse = calc_mse(imputed_X, train_X_intact, indicating_mask)
    print(f"✅ The MSE of TRMF imputation is: {mse:.4f}")


if __name__ == "__main__":
    main()
